---
title: "Homework 5"
author: "Yiying Wu"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## 1
Read data
```{r,message=FALSE}
urlfile = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

homicide_data <- read_csv(url(urlfile))|>
                  janitor::clean_names()

```

Prepare data
```{r}
homicide_summary=homicide_data|>
  unite("city_state", city, state, sep = ", ") |>
  group_by(city_state) |>
  summarize(
    Total_Homicides = n(),
    Unsolved_Homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest")))
```

Proportion test for Baltimore, MD
```{r}
baltimore_data <- filter(homicide_summary, city_state == "Baltimore, MD")
baltimore_test <- prop.test(baltimore_data$Unsolved_Homicides, baltimore_data$Total_Homicides)
baltimore_test |> broom::tidy()
```

Proportion test for all cities
```{r,message=FALSE,warning=FALSE}
all_cities_test <- homicide_summary %>%
  mutate(
    test_result = map2(Unsolved_Homicides, Total_Homicides, ~prop.test(.x, .y)),
    tidy_result = map(test_result, broom::tidy),  # Specify broom::tidy directly
    city_state = city_state  # Preserve city_state in the final result
  ) %>%
  select(-test_result) %>%  # Remove the test_result column
  unnest(tidy_result)

all_cities_test=all_cities_test|>select(city_state, estimate, conf.low, conf.high)
all_cities_test
```

Create a plot that shows the estimates and CIs for each city
```{r, fig.width = 10}
ggplot(all_cities_test, aes(x=reorder(city_state, estimate), y=estimate)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high), width=.2) +
  coord_flip() +
  xlab("City, State") +
  ylab("Proportion of Unsolved Homicides") +
  ggtitle("Proportion of Unsolved Homicides in Various Cities")
```

